# Generated by Django 4.1.1 on 2022-10-07 07:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hosts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CVEScannerV2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("port", models.CharField(max_length=10)),
                ("state", models.CharField(max_length=10)),
                ("service", models.CharField(max_length=20)),
                ("version", models.CharField(max_length=100)),
                ("cves", models.CharField(max_length=20)),
                ("cve_data", models.JSONField(default=dict)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cvescannerv2",
                        to="hosts.host",
                    ),
                ),
            ],
        ),
    ]
