# Generated by Django 4.1.1 on 2022-10-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_sslyze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslyze',
            name='date_scans_completed',
        ),
        migrations.RemoveField(
            model_name='sslyze',
            name='date_scans_started',
        ),
    ]
