# Generated by Django 4.1.1 on 2022-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0003_remove_sslyze_date_scans_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslyze',
            name='connection_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sslyze',
            name='connectivity_error_trace',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
