# Generated by Django 4.1.1 on 2022-10-06 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0004_alter_sslyze_connection_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVEScannerV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=100)),
                ('cves', models.CharField(max_length=20)),
                ('cveid', models.CharField(max_length=50)),
                ('cvssv2', models.CharField(max_length=20)),
                ('cvssv3', models.CharField(max_length=20)),
                ('exploit_db', models.CharField(max_length=10)),
                ('metasploit', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvescannerv2', to='scanners.host')),
            ],
        ),
    ]
