# Generated by Django 4.1.1 on 2022-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0005_cvescannerv2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvescannerv2',
            name='cveid',
        ),
        migrations.RemoveField(
            model_name='cvescannerv2',
            name='cvssv2',
        ),
        migrations.RemoveField(
            model_name='cvescannerv2',
            name='cvssv3',
        ),
        migrations.RemoveField(
            model_name='cvescannerv2',
            name='exploit_db',
        ),
        migrations.RemoveField(
            model_name='cvescannerv2',
            name='metasploit',
        ),
        migrations.AddField(
            model_name='cvescannerv2',
            name='cve_data',
            field=models.JSONField(default=dict),
        ),
    ]
