# Generated by Django 4.1.1 on 2022-10-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanners', '0002_whatweb_wafwoof_dirby'),
        ('scanners', '0006_remove_cvescannerv2_cveid_remove_cvescannerv2_cvssv2_and_more'),
    ]

    operations = [
    ]
