# Generated by Django 4.1.3 on 2022-11-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='host_name',
            new_name='domain_name',
        ),
    ]
