# Generated by Django 4.1.3 on 2022-12-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0002_rename_host_name_host_domain_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True, null=True, unique=True),
        ),
    ]
